root=r"C:\Users\AIA\MsaProject\DjangoServer"
algorithms=f"{root}\\basic\\algorithms"
aitrater=f"{root}\\basic\\dlearn\\aitrater"
fashion=f"{root}\\basic\\dlearn\\fashion"
fruits=f"{root}\\basic\\dlearn\\fruits"
iris=f"{root}\\basic\\dlearn\\iris"
lstm=f"{root}\\basic\\dlearn\\lstm"
mnist=f"{root}\\basic\\dlearn\\mnist"
bicycle=f"{root}\\basic\\mlearn\\bicycle"
nlp=f"{root}\\basic\\nlp"
pythonic=f"{root}\\basic\\pythonic"
webcrawler=f"{root}\\basic\\webcrawler"
comments=f"{root}\\blog\\comments"
posts=f"{root}\\blog\\posts"
tags=f"{root}\\blog\\tags"
views=f"{root}\\blog\\views"
pythonic=f"{root}\\basic\\pythonic"
cinemas=f"{root}\\multiplex\\cinemas"
movies=f"{root}\\multiplex\\movies"
showtimes=f"{root}\\multiplex\\showtimes"
theater_tickets=f"{root}\\multiplex\\theater_tickets"
theater=f"{root}\\multiplex\\theater"
users=f"{root}\\security\\users"
carts=f"{root}\\shop\\carts"
categories=f"{root}\\shop\\categories"
deliveries=f"{root}\\shop\\deliveries"
products=f"{root}\\shop\\products"



