export default context = {
    server : "http://127.0.0.1:8000/",
    analysis : "api/analysis/", 
    basics : "api/basics/",
    dlearn : "api/dlearn/",
    mlearn : "api/mlearn/",
    nlp : "api/nlp/",
    todos : "api/todos/",
    vision : "api/vision/",
    comments : "blog/comments/",
    posts : "blog/posts/",
    tags : "blog/tags/",
    views : "blog/views/",
    main : "common/main/",
    cinemas : "multiplex/cinemas/",
    movies : "multiplex/movies/",
    showtimes : "multiplex/showtimes/",
    theater_tickets : "multiplex/theater_tickets/",
    theaters : "multiplex/theaters/",
    users : "security/users/",
    carts : "shop/carts/",
    categroies : "shop/categories/",
    deliveries : "shop/deliveries/",
    orders : "shop/orders/",
    products : "shop/products/"
}
